# Generated by Django 4.0.4 on 2022-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_trip_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='important_files',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_pictures',
            field=models.ImageField(blank=True, default=None, upload_to='mediafiles/'),
        ),
    ]
